-- DragonWave 2026 - Supabase Schema (snake_case version)
-- Ez a verzió elkerüli a PostgreSQL kis- és nagybetű érzékenységéből adódó hibákat.

-- Táblák törlése az újrakezdéshez (Fejlesztés alatt)
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS racers;
DROP TABLE IF EXISTS categories;

-- Racers Table
CREATE TABLE racers (
    id TEXT PRIMARY KEY,
    bib INTEGER UNIQUE,
    category TEXT,
    distance TEXT,
    is_series INTEGER DEFAULT 0,
    status TEXT DEFAULT 'registered',
    start_time BIGINT,
    finish_time BIGINT,
    total_time BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Members Table
CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    racer_id TEXT REFERENCES racers(id) ON DELETE CASCADE,
    name TEXT,
    birth_date TEXT,
    otproba_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Categories (Starts) Table
CREATE TABLE categories (
    key TEXT PRIMARY KEY,
    start_time BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS
ALTER TABLE racers ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- Public Access Policies (Csak olvasás engedélyezett a publikus anon kulcsnak)
CREATE POLICY "Public Read Access" ON racers FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON members FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON categories FOR SELECT USING (true);

-- Service role teljes hozzáférés (backend szerveroldali műveletekhez)
CREATE POLICY "Service Role Full Access" ON racers FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access" ON members FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Service Role Full Access" ON categories FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Checkpoints Table
CREATE TABLE IF NOT EXISTS checkpoints (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    racer_bib BIGINT NOT NULL,
    checkpoint_name VARCHAR(255) NOT NULL,
    timestamp BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE checkpoints ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Access" ON checkpoints FOR SELECT USING (true);
CREATE POLICY "Service Role Full Access" ON checkpoints FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Performance Indexes (Lemez I/O és lekérdezés optimalizálás)
CREATE INDEX IF NOT EXISTS idx_members_racer_id ON members(racer_id);
CREATE INDEX IF NOT EXISTS idx_checkpoints_racer_bib ON checkpoints(racer_bib);
CREATE INDEX IF NOT EXISTS idx_racers_status ON racers(status);
CREATE INDEX IF NOT EXISTS idx_racers_category ON racers(category);
